language: node_js
node_js:
- 8.11
- 10
after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
cache:
  yarn: true
env:
  global:
    secure: MFu+i9BnaWpmsZlg7J681wd7xP/zHs6GpBGwnztxTPiCt3MWKrmLVJMcCWUKFZ83dmvQS1oP/uz/rEg06XsadG7luQlJH5pXKnymPiCq9mPqtuj/gxZNhZPPzW5ziEHZpWRkyeyHX3YbyapiLzNGoT4zdvULaT7VszUiJzbaoO5bYCn2cGB9suTJaVGHPdc0qFWqdsI+zU5i0Xq/M1/hi87rX/osyR0jlqp9hpmWFM5aaoWUCdnPhpOIt1BHrtFLbD+cuJlmbY80NTFrgvZ1jC2qdNn1TFuKe4SXSImuQnxjGjRP6N1bbwbmEaby11KxkHWBvDYLzDXQnaZ3joyq/7uAPTi+l4w7bF65mjmjauNwsfkk5GYGAKqAuaklVmD6grRvaKsX9MGdnDQarAihFBv0lx8TmlL7/wxhAT0qBUcX25kRQGWAKqMPcZnETM2GXhsdn/FEwIsp+8nA8NNQAmoUwKpPNkAKtsuTv4bRFxCA2GvIATqGtLdwKpgTnCHC4zWUdZ55yPxWDs7JLH9vdsQ9w9p4f/9okqn9IHh97uYM3yHZebl4sxKm6rn7j+KYwsbvksmf7IlZQ8meXVObMZhDm+sHido+VzLeVuCPdvuh4GFKoS0/EeMckQ7lXuidDzMhdouB9sGb3QqpLvZpyIdxqc8cmWFwVr4c+Qz9LX8=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  api_key:
    secure: py4dDwMABSKu0SzqncVFPpTEI084Ufbr1heA+m1xo8Ye2VpsWhhY0DN6PRkBnTr9Oq8xJNUyKby5ndfAVc0B11dOoT/Sgex5pF/K370of803/eH/r//l8LLpZRyUYCaEBmTJGeQX5WvypVuCrtNNpg1XFlkUgXH1VUgfj/VM5afG+72JwQqvav0KygKLMCICI4YK5RO7u2TbZl97PwBhnTWeohCDLllndF7qU5RHd/pgqeseXELc2Xj1JRwM9SBNga1XZclVcmOYUM/hmJnt/VY2R9yHJAQ43/uwaOJBd9gCoAPVW17UxqGouxcf+6W6KLCs9rBaGnV4Og+9Pb57+xqhIUjDKClTBgAo82E9I1c7vJZA+lbe276OwzIRxr012TjZ1tiCRWp2UyblVjLk0VzC4pc7ayBaWbCvJUGg5jRc/Bnyy4DDQ8cWg6acA6s7RLaU6oBu17AGnvq0FIDdvwaJVjODy3Pn8n/FLC0ZILSCy2FDBOR7DrSoPnKsrNOPYxpV9GUxiDH7IutUwQJlfaAq/ygVTh1Apyc3vrk2aO5Cuz5wlN3MqtTi9g6eMbExOUrusR21uhKGXMSGNaPKBWkzApFQM8ys5HGLhVrpzcIfXNSDetChvFPlN94wQdC/juHruE3r3sckbXDTw0r4OX0tPTYtFEZMOogmzV4gImQ=
  on:
    tags: true
    repo: actano/advocate
    node: 8
