language: node_js
node_js:
- 8.9
after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
cache:
  yarn: true
env:
  global:
    secure: MFu+i9BnaWpmsZlg7J681wd7xP/zHs6GpBGwnztxTPiCt3MWKrmLVJMcCWUKFZ83dmvQS1oP/uz/rEg06XsadG7luQlJH5pXKnymPiCq9mPqtuj/gxZNhZPPzW5ziEHZpWRkyeyHX3YbyapiLzNGoT4zdvULaT7VszUiJzbaoO5bYCn2cGB9suTJaVGHPdc0qFWqdsI+zU5i0Xq/M1/hi87rX/osyR0jlqp9hpmWFM5aaoWUCdnPhpOIt1BHrtFLbD+cuJlmbY80NTFrgvZ1jC2qdNn1TFuKe4SXSImuQnxjGjRP6N1bbwbmEaby11KxkHWBvDYLzDXQnaZ3joyq/7uAPTi+l4w7bF65mjmjauNwsfkk5GYGAKqAuaklVmD6grRvaKsX9MGdnDQarAihFBv0lx8TmlL7/wxhAT0qBUcX25kRQGWAKqMPcZnETM2GXhsdn/FEwIsp+8nA8NNQAmoUwKpPNkAKtsuTv4bRFxCA2GvIATqGtLdwKpgTnCHC4zWUdZ55yPxWDs7JLH9vdsQ9w9p4f/9okqn9IHh97uYM3yHZebl4sxKm6rn7j+KYwsbvksmf7IlZQ8meXVObMZhDm+sHido+VzLeVuCPdvuh4GFKoS0/EeMckQ7lXuidDzMhdouB9sGb3QqpLvZpyIdxqc8cmWFwVr4c+Qz9LX8=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: h9JTDWxvC9ip+EUTrVe14aP1b5s4/+ffLupBhZWilFFZoW4d0DdD/NkxL+xRUjY51busqqoyMMe0nDYCgg1Jlmfu81Q7ExIt65lbArg1zDK19vpdo1YAdosgNEf4tJum4CO1T3OxksjD9VKT9WBfFXPlYMFtrgdVReSqx3omHVyUOWx4R2SYNCvaWftieM5Kuw7Ba3/V7CrzGi+HFOc+YQYcbXSkGgfC7WHZUiTYGG9PolDoeB67Xi3wcDoblpWgI454UYgNDAkWoBZ2DaC4gXEG/+XNoxBr1YL61h0tFvg1kQkvDsKJVQwhB5zznNMOCMFTlt0qR7T+08wYNsuCtXo/7yAuelyNwjIUSBGNNAoCdoJ7ePnfZLYrV0DQ8GO5+MiIfVXUB+3Ig9pov7gwC8jyvrJiHIMry4oTDU6aivNrtHX6uh043+xjAdnNF+h1uR2FfBUASDfge9IwTD6yX0xeKl/u60pO/G0wXQ9FhpJ3swTZnFlFnXqrwYqr1O0dgcii/a9E8HMoqSj5x0vK5+YJfK5Kn9mucEjfHqa5MxgG+yNxSYdO+w9BRIwHKKAFj9kLL/MiYUcdo9vpv1vtiSkHJkpe3/Prd9AH0t6jUVSmNJ67jP0UVE5chKO0gQ0Oi98ueWggxF90nIfWskgkAIq+8vmlkP83EXdh2s3mN2w=
  on:
    tags: true
    repo: actano/advocate
