language: node_js
node_js:
- 8.9
after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

cache:
  yarn: true

# Greenkeeper update lockfile
env:
  global:
    secure: MFu+i9BnaWpmsZlg7J681wd7xP/zHs6GpBGwnztxTPiCt3MWKrmLVJMcCWUKFZ83dmvQS1oP/uz/rEg06XsadG7luQlJH5pXKnymPiCq9mPqtuj/gxZNhZPPzW5ziEHZpWRkyeyHX3YbyapiLzNGoT4zdvULaT7VszUiJzbaoO5bYCn2cGB9suTJaVGHPdc0qFWqdsI+zU5i0Xq/M1/hi87rX/osyR0jlqp9hpmWFM5aaoWUCdnPhpOIt1BHrtFLbD+cuJlmbY80NTFrgvZ1jC2qdNn1TFuKe4SXSImuQnxjGjRP6N1bbwbmEaby11KxkHWBvDYLzDXQnaZ3joyq/7uAPTi+l4w7bF65mjmjauNwsfkk5GYGAKqAuaklVmD6grRvaKsX9MGdnDQarAihFBv0lx8TmlL7/wxhAT0qBUcX25kRQGWAKqMPcZnETM2GXhsdn/FEwIsp+8nA8NNQAmoUwKpPNkAKtsuTv4bRFxCA2GvIATqGtLdwKpgTnCHC4zWUdZ55yPxWDs7JLH9vdsQ9w9p4f/9okqn9IHh97uYM3yHZebl4sxKm6rn7j+KYwsbvksmf7IlZQ8meXVObMZhDm+sHido+VzLeVuCPdvuh4GFKoS0/EeMckQ7lXuidDzMhdouB9sGb3QqpLvZpyIdxqc8cmWFwVr4c+Qz9LX8=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test
after_script: greenkeeper-lockfile-upload

deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  api_key:
    secure: VXsTPdlIvkkVkFD2p1cVXCbg+MWjMmMwwZ0lmMGohHqcLjWHrPlnqyHfdvnkU3S0ZMUBnf9e0hrsjQRqZ1t8GE3efTx+dYFYO/DxvKF8TQFYmjeS4PbV2Cw/SX16/B55guVx1U7TlaQ5nB0njktVmSzWhWYrS/U7v3yxj29o1PHYiL9iF+2UXXtWEQidU9EueG+Msbe4LNnzMQ2ba4RVh5YlP3mCVhKRJJBFXd3g3K/Yj5nITeo6zS8WDWTwVaFMS+a1/u6lrxgOiT9ZdJDhFfzE3Ucc37ZSmidHpdQSm14m9BxmkFfXvp5CLcuCGQSQyS2z5eS1drQDGZEGU4pPgwrgyzVqRGEM/yV7e8YGC/voSAND8Druj6ygmAujeqVPK4upy3IRmbV7D1i69DApwncCc2lXLLpjoE4p3bwuB/+bDPMn6K7hocXWluN2RKwHr8mNjy9tluIKuXuPLjF6iLrDaFvVq4JuR72jhbc4HuxeC2/ouny8hNhnrFNKzdIOWPoT7oct/5aUQ2DIRvaAcIWSSUD6ItlkvcBrazkZ0nBqiRjujaZAcWWwSWMFibNdZlRb9cfVfTyb4obfL0+ZW6Tw8AGUdj03oNDZa4AxUOcQtmsWtypetB50yYXtpfXp4IRG3eYYI4/krrpvgbfnzUmcWyTWWO/8hJvg1MghWEM=
  on:
    tags: true
    repo: actano/advocate
    node: 8.9
