language: node_js
node_js:
- 5.10.1
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: eZbAlcDwW7Vm0ovAqO9pd0U2n8OeZbWyk+obeIpycjhL4QfBF614bUqgcwQoGPBnKObQlmz1vMPtmWg8Eqa+o+CCsb62lTesFTvqrxpkaNuv4NrZYInZH9ltDQUV5JtmwcXILeHWOAXxorMbeOKwNmasbgIzGw6FxfUkPuXBu61cpx3vH8zL1QzSKg5yP1F+nqTOOb1S6fs2n9hzEulyo0XVNu90mrMrn8dXzP6wWXLCK6Iplpv+1VHsdxZa9DWY0EsEKBdCbKBrQtVgT4HWhlvBMxajOEhj0EBsm9JV4ZCsQBQXcOP31TCpZ38/pzoHn4Wg/TQe7ByjWGIXye66Gjr3xjQL0PnWion8X1m8z8B48erS6gVsN0mHMR2zZ4K7/22ztgecErL7faUgNXDILbP8hPYe6POt9Tgo4UN1wh49MVCEYLXPlmpOCzqJhl5Gtkm6SzP6iNpA73l91HPVPBm0vuYtZ2sZREkAESRNI6mCKg8rX6dMgAzOV53K4c1d73I4FM0o0CtCs3X53P+tbPfbD7gykTIGybknMWc1Hi3AQczp1m3LUU6hO1uqTbM+aRbPRDBvtetQBtLvwc5hARue6pa1vzXV8LrMNNuHpzV8MKm5QpWpgxQZmZB184HgP8VMzvlY5mTBBecl3b0GKVQRn3QTuBWzngn914YLhqY=
  on:
    tags: true
    repo: actano/advocate
